name: "Seif-Allah's Blog"
title: "Seif-Allah's Blog"
description: "“I wanted to save the world.”"
logo: 'assets/images/cover.png'
logo-footer: 'assets/images/cover_footer.png'
favicon: 'assets/images/logo.png'
baseurl: "/seifallahhomrani1.github.io"
google_analytics: UA-181011093-2  
disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/
email: seif.allah.homrani@gmail.com

# Authors
authors:
  Seif-Allah:
    name: Seif-Allah
    display_name: Seif-Allah
    gravatar: 87daf283c8d29fa33059e59cf5d183bb
    email: seif.allah.homrani@gmail.com
    web: seifallahhomrani1.social
    description: "Author of this blog, a script kiddie and an anarchist."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed



exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
