title: Seif-Allah Homrani
email: seifallahhomrani1@gmail.com
#description: >- # this means to ignore newlines until "baseurl:" Seif-Allah Homrani's PortfolioIT student, programmer, coffee addicted
baseurl: "/" # the subpath of your site, e.g. /blog
twitter_username: seifallah1
github_username:  seifallahhomrani1
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
header_pages: 
- index.markdown
- about.markdown
- Posts.md

google_analytics: UA-181011093-2

style: dark
listen_for_clients_preferred_style: false
footer : Boring ? <a href="javascript:(function () {var s = document.createElement('script');s.setAttribute('src', '/fontBomb/js/main.js');document.body.appendChild(s);}());" title="What are waiting for ?"><strong>BOMB IT NOW !</strong></a>
lang: en


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
